version: "3"
services:
  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: lol
      POSTGRES_PASSWORD: password
      POSTGRES_DB: easyspeak
    ports:
      - 5432:5432